export const DEFAULT_REVIEWS = [
  {
    id: 1,
    userName: "Tendy",
    comment: "Don't forget bear spray",
    experienceRating: 4,
    createdAt: "2023-06-15",
  },
  {
    id: 2,
    userName: "Babak",
    comment: "Hydration is key",
    experienceRating: 4,
    createdAt: "2023-06-10",
  },
  {
    id: 3,
    userName: "Tendy Jr.",
    comment: "Don't stand on a cliff to take a photo",
    experienceRating: 1,
    createdAt: "2023-06-01",
  },
  {
    id: 4,
    userName: "Michael",
    comment: "Cliff bars are delicious",
    experienceRating: 1,
    createdAt: "2023-06-01",
  },
  {
    id: 5,
    userName: "Syed",
    comment: "Cheap to drive to by electric car",
    experienceRating: 1,
    createdAt: "2023-06-01",
  },
  {
    id: 6,
    userName: "Has",
    comment: "Great for picnics",
    experienceRating: 1,
    createdAt: "2023-06-01",
  },
  {
    id: 7,
    userName: "Grizzly",
    comment: "I am friendly",
    experienceRating: 1,
    createdAt: "2023-06-01",
  },
  {
    id: 8,
    userName: "Coyote",
    comment: "Keep small dogs on leash",
    experienceRating: 1,
    createdAt: "2023-06-01",
  },
];
