export const SET_SEARCH_ACTIVITIES = "SET_SEARCH_ACTIVITIES";

export const SET_SEARCH_STATES = "SET_SEARCH_STATES";

export const SET_SEARCH_AMENITIES = "SET_SEARCH_AMENITIES";

export const CLEAR_SEARCH = "CLEAR_SEARCH";
